#!/usr/bin/env bash
# ==============================================================================
# Auto-generated by System Control Center (Google Material Design 3)
# ==============================================================================
set -u
[ -n "${DISPLAY:-}" ] || exit 0

# 1. Keyboard Repeat Rate & Screen Blanking
if command -v xset >/dev/null 2>&1; then
    xset r rate 280 40 2>/dev/null || true
    xset s off -dpms 2>/dev/null || true
fi

# 2. Keyboard Layout
if command -v setxkbmap >/dev/null 2>&1; then
    setxkbmap -option '' >/dev/null 2>&1 || true
    setxkbmap -layout "us,ru" -option "grp:win_space_toggle" >/dev/null 2>&1 || true
fi

# 3. Pointer Devices (libinput)
command -v xinput >/dev/null 2>&1 || exit 0

apply_prop() {
    local device_name="$1"
    local property_name="$2"
    shift 2
    while IFS= read -r dev_id; do
        [ -n "$dev_id" ] || continue
        xinput list-props "$dev_id" 2>/dev/null | grep -Fq "$property_name" || continue
        xinput set-prop "$dev_id" "$property_name" "$@" >/dev/null 2>&1 || true
    done < <(xinput list --id-only "$device_name" 2>/dev/null || true)
}

# Compx VXE Mouse 1K Dongle
apply_prop "Compx VXE Mouse 1K Dongle" 'libinput Accel Profile Enabled' 1 0 0
apply_prop "Compx VXE Mouse 1K Dongle" 'libinput Accel Speed' 0.00
apply_prop "Compx VXE Mouse 1K Dongle" 'libinput Natural Scrolling Enabled' 0
apply_prop "Compx VXE Mouse 1K Dongle" 'libinput Left Handed Enabled' 0
apply_prop "Compx VXE Mouse 1K Dongle" 'libinput Middle Emulation Enabled' 0

# Gaming Keyboard Mouse
apply_prop "Gaming Keyboard Mouse" 'libinput Accel Profile Enabled' 0 1 0
apply_prop "Gaming Keyboard Mouse" 'libinput Accel Speed' 0.00
apply_prop "Gaming Keyboard Mouse" 'libinput Natural Scrolling Enabled' 0
apply_prop "Gaming Keyboard Mouse" 'libinput Left Handed Enabled' 0
apply_prop "Gaming Keyboard Mouse" 'libinput Middle Emulation Enabled' 0
