#!/bin/sh

choice=$(printf " Lock\n󰍃 Logout\n Reboot\n Shutdown" | \
  rofi -dmenu -i -p "Power")

case "$choice" in
  " Lock") i3lock ;;
  "󰍃 Logout") i3-msg exit ;;
  " Reboot") systemctl reboot ;;
  " Shutdown") systemctl poweroff ;;
esac
