# ==============================================================================
# Xorg ServerFlags Tweaks (Gaming & Media Stability)
# ==============================================================================
Section "ServerFlags"
    # Разрешить экстренный перезапуск X-сервера по комбинации Ctrl+Alt+Backspace
    Option "DontZap" "false"

    # Отключение энергосбережения и гашения экрана на уровне ядра Xorg
    # Предотвращает засыпание дисплеев во время гейминга (с геймпадами), просмотра видео и простоя
    Option "BlankTime"   "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime"     "0"
EndSection
