# ==============================================================================
# Xorg Raw 1:1 Mouse Input (Flat Acceleration Profile)
# ==============================================================================
# Отключает любую программную и кривую акселерацию для всех указателей (мышей).
# Обеспечивает честное прямое соотношение 1:1 перемещения курсора без сглаживания и рывков.
Section "InputClass"
    Identifier "Libinput Pointer Flat Acceleration"
    MatchIsPointer "yes"
    MatchDriver "libinput"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0"
EndSection
